# Generated by Django 2.0.13 on 2019-06-15 23:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190615_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mybio', ckeditor.fields.RichTextField(max_length=700)),
                ('ptitile', models.CharField(max_length=200)),
                ('ptext', ckeditor.fields.RichTextField()),
                ('location', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
            ],
        ),
    ]
