# Generated by Django 2.0.13 on 2019-06-16 00:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_aboutme_mybio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptitile', models.CharField(max_length=200)),
                ('ptext', ckeditor.fields.RichTextField()),
                ('location', models.CharField(max_length=200)),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField(blank=True, null=True)),
                ('duration', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Aboutme',
        ),
    ]
