# Generated by Django 2.0.13 on 2019-06-16 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190616_0617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='duration',
            new_name='designation',
        ),
    ]
