# Generated by Django 2.0.13 on 2019-06-16 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_aboutme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='mybiotext',
            field=models.CharField(max_length=1000),
        ),
    ]
