# Generated by Django 2.0.13 on 2019-06-16 04:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190616_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='mybiotext',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
