# Generated by Django 2.0.13 on 2019-06-16 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190616_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='greettext',
            field=models.CharField(default='Welcome', max_length=200),
        ),
    ]
