# Generated by Django 2.0.13 on 2019-06-16 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_aboutme_greettext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutme',
            old_name='mybiotext',
            new_name='mybio',
        ),
    ]
