# Generated by Django 2.0.13 on 2019-06-16 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190616_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutme',
            old_name='mybio',
            new_name='mybiotext',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='greettext',
        ),
    ]
