# Generated by Django 2.0.13 on 2019-06-16 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='qdate',
            field=models.DateTimeField(default=datetime.date(2019, 6, 16)),
        ),
    ]
