# Generated by Django 2.0.13 on 2019-06-16 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20190616_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='qdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
