# Generated by Django 2.0.13 on 2019-06-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20190616_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='qdate',
            field=models.DateField(),
        ),
    ]
