# Generated by Django 2.0.13 on 2019-06-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20190616_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
