# Generated by Django 2.0.13 on 2019-06-16 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20190616_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quote',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
