# Generated by Django 2.0.13 on 2019-06-26 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20190616_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='aimage',
            field=models.ImageField(blank=True, upload_to='blog_images', validators=[django.core.validators.FileExtensionValidator(['jpg', 'gif', 'png'])]),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_pics', validators=[django.core.validators.FileExtensionValidator(['jpg', 'gif', 'png'])]),
        ),
    ]
